[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn server:app"
healthcheckPath = "/"
healthcheckTimeout = 100

[deploy.env]
PYTHON_VERSION = "3.9"
PYTHONUNBUFFERED = "1"

[[services]]
name = "chroma-db"
type = "persistent-disk"
size = "1GB"
mountPath = "/app/chroma" 
